'use strict';
const axios = require('axios');
const logger = require('./logger');
const state = require('../state');

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const CHAT_ID   = process.env.TELEGRAM_CHAT_ID;

function isConfigured() {
  return !!(BOT_TOKEN && CHAT_ID);
}

async function sendMessage(text) {
  if (!isConfigured()) return false;
  try {
    await axios.post(
      `https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`,
      { chat_id: CHAT_ID, text, parse_mode: 'Markdown', disable_web_page_preview: true },
      { timeout: 10000 }
    );
    state.telegram.messagesSent++;
    return true;
  } catch (err) {
    logger.error('telegram', `Failed to send message: ${err.message}`);
    return false;
  }
}

async function sendSignal({ symbol, direction, confidence, riskReward, sl, tp, price, reasons = [] }) {
  const arrow = direction === 'long' ? '🟢 LONG' : '🔴 SHORT';
  const rrStr = riskReward ? `1:${riskReward.toFixed(2)}` : '—';
  const slStr = sl ? sl.toFixed(6) : '—';
  const tpStr = tp ? tp.toFixed(6) : '—';
  const priceStr = price ? price.toFixed(6) : '—';
  const reasonsList = reasons.length ? reasons.map((r) => `  • ${r}`).join('\n') : '  • Multi-TF confluence';

  const text = [
    `📊 *AI Signal: ${symbol}*`,
    `Direction: *${arrow}*`,
    `Entry Price: \`${priceStr}\``,
    `Confidence: *${confidence}%*`,
    `Risk:Reward: *${rrStr}*`,
    `Stop Loss: \`${slStr}\``,
    `Take Profit: \`${tpStr}\``,
    `Confirmations:\n${reasonsList}`,
    `_Generated by AI Trader_`,
  ].join('\n');

  return sendMessage(text);
}

async function sendTradeOpen({ symbol, direction, price, quantity, sl, tp, confidence }) {
  const arrow = direction === 'long' ? '🟢 BUY' : '🔴 SELL';
  const text = [
    `✅ *Trade Opened: ${symbol}*`,
    `Direction: *${arrow}*`,
    `Price: \`${(+price).toFixed(6)}\``,
    `Quantity: \`${(+quantity).toFixed(6)}\``,
    `Stop Loss: \`${sl ? (+sl).toFixed(6) : '—'}\``,
    `Take Profit: \`${tp ? (+tp).toFixed(6) : '—'}\``,
    `Confidence: *${confidence}%*`,
  ].join('\n');
  return sendMessage(text);
}

async function sendTradeClose({ symbol, direction, entryPrice, exitPrice, pnl, result }) {
  const emoji = pnl >= 0 ? '💰' : '📉';
  const text = [
    `${emoji} *Trade Closed: ${symbol}*`,
    `Direction: *${direction.toUpperCase()}*`,
    `Entry: \`${(+entryPrice).toFixed(6)}\``,
    `Exit: \`${(+exitPrice).toFixed(6)}\``,
    `PnL: *${pnl >= 0 ? '+' : ''}${(+pnl).toFixed(4)} USDT*`,
    `Result: *${result.toUpperCase()}*`,
  ].join('\n');
  return sendMessage(text);
}

async function sendError(scope, message) {
  if (!isConfigured()) return false;
  const text = `⚠️ *Error [${scope}]*\n\`${message}\``;
  return sendMessage(text);
}

module.exports = {
  isConfigured,
  sendMessage,
  sendSignal,
  sendTradeOpen,
  sendTradeClose,
  sendError,
};
